#ifndef _CONSTANTS_
#define _CONSTANTS_

#define WIDTH 1024
#define HEIGHT 768

#define HITPOINT_SIZE 3

#define SCREEN_CORNER_DISTANCE 30
#define SCREEN_CORNER_SIZE 15

#define PROJ_CORNER_SIZE 5

#define CALIBRATION_WAIT_FRAMES 15

#endif
