#ifndef _CONSTANTS_
#define _CONSTANTS_

#define WIDTH 1280 //1218
#define HEIGHT 800

#define HITPOINT_SIZE 3

#define SCREEN_CORNER_DISTANCE 30
#define SCREEN_CORNER_SIZE 15

#define PROJ_CORNER_SIZE 5

#define CALIBRATION_WAIT_FRAMES 20

#define THRESHOLD 33
#define HUE 30
#define HUE_VARIANCE 3
#define SATURATION 100
#define SATURATION_VARIANCE 20
#define VALUE 100
#define VALUE_VARIANCE 20
#define MIN_BLOB_SIZE 1000
#define MAX_BLOB_SIZE 3000

#define PLOT_SIZE 500

#define ANIMATION_SPEED 7

#endif
